### ISSUE TITLE
[Bug]Tmds.DBus.Protocol.DBusException: org.freedesktop.DBus.Error.UnknownMethod: Method "CreateInputContext" with signature "s" on interface "org.freedesktop.IBus.Portal" doesn't exist

### ISSUE THREAD

**Issue by upmferraz** [ryujinx-mirror/ryujinx#29]
### Description of the issue

Crashing while game starts on Steam Deck

### Reproduction steps

Start a game

### Log file

00:00:04.698 |E| UI : [Error] [IME] Unable to create IME input context:
Tmds.DBus.Protocol.DBusException: org.freedesktop.DBus.Error.UnknownMethod: Method "CreateInputContext" with signature "s" on interface "org.freedesktop.IBus.Portal" doesn't exist

   at Tmds.DBus.Protocol.DBusConnection.MyValueTaskSource`1.System.Threading.Tasks.Sources.IValueTaskSource<T>.GetResult(Int16 token)
   at Tmds.DBus.Protocol.DBusConnection.CallMethodAsync[T](MessageBuffer message, MessageValueReader`1 valueReader, Object state)
   at Tmds.DBus.Protocol.Connection.CallMethodAsync[T](MessageBuffer message, MessageValueReader`1 reader, Object readerState)
   at Avalonia.FreeDesktop.DBusIme.IBus.IBusX11TextInputMethod.Connect(String)
   at Avalonia.FreeDesktop.DBusIme.DBusTextInputMethodBase.OnNameChange(Exception e, ValueTuple`3 args) (IBusX11TextInputMethod #41515225)
00:00:06.048 |E| UI : [Error] [IME] Error while destroying the context:
Tmds.DBus.Protocol.DBusException: org.freedesktop.DBus.Error.UnknownMethod: Method Destroy is not implemented on interface org.freedesktop.IBus.Service

### OS

Steam OS

### Ryujinx version (revision hash)

r0b111b3

**Comment by enbyte** [comment]
can you put the output log in a codeblock or upload it to pastebin so it's easier to read?

**Comment by upmferraz** [comment]
sure https://pastebin.com/u7nb9igp

**Comment by jdmg94** [comment]
I get the same error trying to install the firmware, the prod.keys are on the system folder but the application errors out with this exact error on the logs
